### ISSUE TITLE
id は恒等関数なので，変数を表すには var とかいうのを使った方が良いかも

### ISSUE THREAD

**Issue by sano-jin** [tkyawa/project_research_a#1]
# id は恒等関数なので，変数を表すには var とかいうのを使った方が良いかも
```haskell
data AExpr = Id String | ...
```
とか
```haskell
getVal env id  = lookup id env 
```
とかで， `id` という変数を使っているけど，個人的には若干違和感があるかもなぁと．

Variable（変数）をちょっと短くして var とかすることが多いかな．

逆に id の方が自然（go の本とかがこっちだったりとか）だったら教えてください．

クッソ細かい話．

**Comment by kyawaway** [comment]
そこかなり迷ったのですが，
```
identifier = Token.identifier lexer
```
を識別子用のパーサとしていたので，識別子として出てくるものはすべてidentifierが連想できるような文字列にしておいた方が全体として見通しが良くなるかなぁみたいな思考でidとおいてました．
でも確かにその部分だけ見ると絶対varの方がわかりやすいですよね ; ;　
特に
```
data AExpr = Id String | ...
```
に関してはAExprに属している時点で
```
evalAExpr :: Env -> AExpr -> Integer
.
.
.
evalAExpr env (Id x) = test $ getVal env x 
```
のように現状絶対に値を入れる変数以外の用途(関数のための識別子とか)にはなり得ませんしね...

**Comment by sano-jin** [comment]
なるほどね〜．単にぼくが見慣れてないだけという可能性もあります(^^)

まぁ一応補足してくれたのの補足というか蛇足としては，この先クロージャ（要は高階関数）を実装するのであれば変数に関数（正確にはクロージャ）を代入・束縛することもあるとは思います．もちろん現時点では先の話だけど．

（あんまりまわりに趣味でインタプリタを書いたりとかしてる人がいなかったので，つい嬉しくなっちゃってギャーギャーうるさく騒いじゃっているかも知れない……）
